# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sleepWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.ApplicationModal)
        Form.resize(320, 240)
        Form.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        Form.setWindowTitle("")
        self.sleep = QtWidgets.QWidget(Form)
        self.sleep.setGeometry(QtCore.QRect(0, 0, 320, 240))
        self.sleep.setMinimumSize(QtCore.QSize(320, 240))
        self.sleep.setMaximumSize(QtCore.QSize(320, 240))
        self.sleep.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.sleep.setAutoFillBackground(False)
        self.sleep.setStyleSheet("background-color: black;")
        self.sleep.setObjectName("sleep")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        pass


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
